### ISSUE TITLE
critical Improvement

### ISSUE THREAD

**Issue by ashiqYousuf** [oldstone7/smalltalk#1]
Always add .gitignore file and dont push your db into github same goes for env files where your credentials are written

**Comment by oldstone7** [comment]
> Always add .gitignore file and dont push your db into github same goes for env files where your credentials are written

Sorry bro my bad. Now how can I revert it? Should I delete the directory or is there any other way to rollback the commits?

**Comment by ashiqYousuf** [comment]
Clone it added .gitignore file and db.sqlite, pycache (as no one is pushing cache ever) file and other important  files containing creds (if any) and then push it. Check stackoverflow also (already there are guys who have commited same mistakes, I too very often).

**Comment by ashiqYousuf** [comment]
Anyways, since this is a dummy project (not much concern here). But keep this thing in mind from always. Always maintain a .gitignore file and take help from https://www.toptal.com/developers/gitignore

Anways u can connect with me if u wish!

And u can close this issue now!
